language: python

python:
  - '3.6'

install:
- travis_retry pip install -r requirements-dev.txt
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- python -m unittest discover
- flake8
- mkdir for_test
- cd for_test
- py.test

after_success:
- coveralls